### ISSUE TITLE
TabPage maintain state

### ISSUE THREAD

**Issue by dannythomas13** [mrpmorris/blazor-university#12]
Firstly thanks for the great content!

I have copied your suggestion for implementing a TabControl and it works great thanks but I am wondering if you can explain why each TabPage is always reset when we revisit and how we might maintain it. An example would be the counter default page keeping its current counter value

**Comment by HandbagCrab** [comment]
It's pretty easy to implement state. First you need to create a state class to hold the state. Create a new class called CounterState and just put a single property to contain the counter.

It should look like:

    public class CounterState
    {
        public int CounterValue { get; set; } = 0
    }

Now in startup.cs, in the ConfigureServices method add the line:

    services.AddScoped<CounterState>();

In Counter.razer add:

    @inject CounterState counterstate

(This should appear just after the page directive)

Now all you need to do is replace "currentCount" with "counterstate.CounterValue" (you can delete the initialization of currentCount as we've already taken care of that in the CounterState class.

    <p>Current count: @counterstate.CounterValue</p>

    private void IncrementCount()
    {
        counterstate.CounterValue++;
    }

So, what's it all doing?

CounterState.cs has a single property called CounterValue that will hold the value from Counter.razor

The line in ConfigureServices tells the dependency injector that we've got a class that we'd like to inject at some point.

In Counter.razor we then inject our CounterState instance calling it counterstate within the current page.

Then we replace currentCount with counterstate.CounterValue so that instead of relying on the original local variable we're now accessing the CounterValue property from our CounterState class.

Now when you click the button to update the value then navigate away from and back to the counter page you'll find the value is persisted between visits.

**Comment by mrpmorris** [comment]
Hi

As @HandbagCrab said, this is just the standard way that Blazor works. If you store your state outside of the component then it will persist across tabs.

I use this for my state - https://github.com/mrpmorris/fluxor
